[project]
name = "topoevals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "persim>=0.3.8",
    "ripser>=0.6.14",
    "torch>=2.9.1",
    "transformers>=4.57.6",
]
